version: '3.8'

services:
  survey-app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./survey.db:/app/survey.db
    environment:
      - NODE_ENV=production
    restart: unless-stopped 